name: Build, push, deploy

env:
  DOCKER_REGISTRY: ghcr.io
  IMAGE_REPOSITORY: compteurs-velo
  KEEL_FQDN: keel.loicgombeaud.com

on:
  push:
    branches:
      - main
      - test
  schedule:
    - cron: '0 12 * * *'

jobs:
  deploy:
    name: Deploy the new image
    runs-on: ubuntu-latest
    steps:
      - run: |
          IMAGE_NAME=$DOCKER_REGISTRY/${{ github.repository_owner }}/$IMAGE_REPOSITORY
          IMAGE_NAME=$(echo $IMAGE_NAME | tr '[A-Z]' '[a-z]') # to lowercase
          echo IMAGE_NAME=$IMAGE_NAME
          curl \
            -u admin:${{ secrets.KEEL_PASSWORD }} \
            -d "{\"name\":\"$IMAGE_NAME\", \"tag\":\"latest\"}" \
            -H "Content-Type: application/json" \
            -X POST https://$KEEL_FQDN/v1/webhooks/native
